import { chromium } from 'playwright-core';
import fs from 'node:fs';
const exe='/home/hrant/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome';
const b=await chromium.launch({executablePath:exe,args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
const page=await ctx.newPage();
const errs=[];
page.on('console',m=>{if(m.type()==='error')errs.push(m.text());});
page.on('pageerror',e=>errs.push('PAGEERROR: '+e.message));
const aw=JSON.parse(fs.readFileSync('data/artworks.json','utf8'));
const start=aw[20].id;
await page.goto('http://localhost:4321/artwork/'+start+'/',{waitUntil:'networkidle'}).catch(()=>{});
await page.waitForTimeout(1500);
const urlBefore=page.url();
const titleBefore=await page.locator('h1').first().textContent();
await page.getByRole('button',{name:'Next artwork'}).click();
await page.waitForTimeout(1000);
const urlAfter=page.url();
const titleAfter=await page.locator('h1').first().textContent();
console.log('title before:',titleBefore);
console.log('title after :',titleAfter);
console.log('url changed :',urlBefore!==urlAfter, urlAfter.split('/artwork/')[1]);
console.log('console errors:',errs.length? JSON.stringify(errs,null,1):'NONE');
await b.close();
