import { chromium } from 'playwright-core';
import fs from 'node:fs';
const exe='/home/hrant/.cache/ms-playwright/chromium-1228/chrome-linux64/chrome';
const b=await chromium.launch({executablePath:exe,args:['--no-sandbox']});
const ctx=await b.newContext({viewport:{width:390,height:844},deviceScaleFactor:2});
const page=await ctx.newPage();
const imgReqs=[];
page.on('requestfinished',async r=>{ if(r.resourceType()==='image'){const h=await r.response().then(x=>x.headerValue('content-length')).catch(()=>null); imgReqs.push({url:r.url().split('/').slice(-2).join('/'), kb: h?Math.round(h/1024):'?'});}});
const aw=JSON.parse(fs.readFileSync('data/artworks.json','utf8'));
await page.goto('http://localhost:4321/artwork/'+aw[20].id+'/',{waitUntil:'networkidle'}).catch(()=>{});
await page.waitForTimeout(2500);
console.log('viewer image requests so far:'); imgReqs.forEach(x=>console.log('  ',x.kb,'KB ',x.url));
const before=imgReqs.length;
const t0=Date.now();
await page.getByRole('button',{name:'Next artwork'}).click();
// wait until a new <img> in viewer reports complete
await page.waitForFunction(()=>{const im=document.querySelector('main img, .touch-pan-y img'); return im && im.complete && im.naturalWidth>0;},{timeout:8000}).catch(()=>{});
console.log('time to next image ready:', Date.now()-t0,'ms');
await page.waitForTimeout(800);
console.log('new image requests after swap:', imgReqs.slice(before).map(x=>x.kb+'KB').join(', ')||'(none new — served from preload cache)');
await b.close();
